server_name: nats

port: 4222
http: 8222

# Logging configuration for centralized Loki pipeline
logtime: true
log_file: "/data/nats.log"

jetstream {
  store_dir: "/data"
}

websocket {
  port: 9222
  no_tls: true
  same_origin: false
}