# nats.conf

# NATS client port
port: 4222

# HTTP monitoring port
http_port: 8222

# Server name
server_name: "local-nats"

# Authentication
authorization {
    # Option 1: Token authentication
    token: "88eab73c32486334dbad5bad67f1a6adabdc5e8eecbf38c4b9e3b6dc3cda6fe0"

    # Option 2: Username and Password authentication
    # users = [
    #     { user: "admin", password: "natspwd" }
    # ]

    
}

jetstream {
    store_dir: "/data/jetstream"
}