[SERVICE]
    Flush        1
    Log_Level    info
    Daemon       Off

[INPUT]
    Name             tail
    Path             /data/nats.log
    Tag              nats.server
    Read_from_Head   true
    Refresh_Interval 2

[OUTPUT]
    Name         loki
    Match        nats.*
    Host         otel-lgtm
    Port         3100
    Labels       service=nats,server=nats,cluster=nats-demo,environment=demo
    Auto_Kubernetes_Labels Off
